feat: support RISC-V

diff --git a/bin/pmctrack-manager b/bin/pmctrack-manager
--- a/bin/pmctrack-manager
+++ b/bin/pmctrack-manager
@@ -1,6 +1,6 @@
 #!/bin/bash
 action=$1
-available_actions=(build version clean build-phi build-user-tools build-android-odroid load-module remove-module)
+available_actions=(build version clean build-phi build-user-tools build-riscv build-android-odroid load-module remove-module)
 
 if [ "$action" == "" ]; then
 	action_str=$( echo ${available_actions[*]} | tr ' ' '|' )
@@ -649,6 +649,137 @@ function do_build_android_odroid(){
 	echo "*** BUILD PROCESS COMPLETED SUCCESSFULLY ***"
 }
 
+function do_build_riscv(){
+	local bitw=64
+	local vendor_id=0
+	local hz_setting=200
+	local vendor_str="RISC-V"
+	local separator="============================================"
+	local cross_compile="$1"
+	local kernel_tree="$2"
+
+	## Not enough arguments?
+	if [ "$kernel_tree" == "" ]; then
+		echo "Usage: pmctrack-manager build-riscv <cross_compile> <kernel-sources-dir>" 
+		exit 1			
+	fi
+
+	if [ ! -d "${kernel_tree}" ]; then
+		echo "Linux kernel sources not found: ${kernel_tree} " 
+		exit 1			
+	fi
+
+	echo "**** Target system information ***"
+	printf "Processor_vendor=${vendor_str}"
+	printf "\n"
+	echo "Kernel_HZ=${hz_setting}"
+	echo "Processor_bitwidth=${bitw}"
+	echo "Cross_compiler=${cross_compile}gcc"
+	echo "*******************************************************************************************"
+	printf "Press ENTER to start PMCTrack's cross-compilation for RISC-V Linux..."
+	read
+	echo "*******************************************************************************************"
+
+	oldp=$PWD
+	
+	## Go to module directory
+	module=riscv
+	modname="mchw_riscv.ko"
+	dir_module="${PMCTRACK_ROOT}/src/modules/pmcs/${module}"
+
+	if [ ! -d ${dir_module} ]; then
+		echo "Module directory not found in the source tree: ${dir_module}"
+		exit 1
+	fi
+
+	## Go to module directory
+	cd ${dir_module}
+
+	## If the ko already exists (clean it)
+	if [ -f ${modname} ]; then
+		echo "Cleaning existing object files for ${modname} module "
+		make -f Makefile.riscv XCOMP=${cross_compile} KERNEL_TREE=${kernel_tree} clean
+		echo "$separator"
+	fi
+
+	echo "Building kernel module $module...."
+	echo "$separator"
+
+	make -f Makefile.riscv XCOMP=${cross_compile} KERNEL_TREE=${kernel_tree} 2>&1
+
+	if [ $? -ne 0 ] ; then
+		printf "Error building ${modname}\nIncomplete build!!\n"
+		exit 1
+	fi
+	echo "Done!!"
+	echo "$separator"
+
+	cd $oldp
+
+## Build libpmctrack
+	builddir="${PMCTRACK_ROOT}/src/lib/libpmctrack"
+
+	if [ ! -d ${builddir} ]; then
+		echo "libpmctrack source directory not found in the source tree: ${builddir}"
+		exit 1
+	fi
+
+	cd $builddir
+
+	## If the library files already exist (clean it)
+	if [ -f libpmctrack.so ] || [ -f libpmctrack.a ]; then
+		echo "Cleaning up existing object files for libpmctrack"
+		make clean
+		echo "$separator"		
+	fi
+
+	echo "Building libpmctrack ...."
+	echo "$separator"
+
+	CC=${cross_compile}gcc make 2>&1
+
+	if [ $? -ne 0 ] ; then
+		printf 'Error building libpmctrack\nIncomplete build!!\n'
+		exit 1
+	fi
+	echo "Done!!"
+	echo "$separator"
+## Build pmc-events and pmctrack
+
+	for command in pmc-events pmctrack
+	do
+		builddir="${PMCTRACK_ROOT}/src/cmdtools/${command}"
+		execfile="${PMCTRACK_ROOT}/bin/${command}"
+		if [ ! -d ${builddir} ]; then
+			echo "${command} source directory not found in the source tree: ${builddir}"
+			exit 1
+		fi
+
+		cd $builddir
+
+		## If the library files already exist (clean it)
+		if [ -f ${execfile} ] ; then
+			echo "Cleaning up existing object files for ${command}"
+			make clean
+			echo "$separator"
+		fi
+
+		echo "Building ${command} ...."
+		echo "$separator"
+
+		CC=${cross_compile}gcc make 2>&1
+
+		if [ $? -ne 0 ] ; then
+			printf 'Error building ${command}\nIncomplete build!!\n'
+			exit 1
+		fi
+		echo "Done!!"
+		echo "$separator"
+	done
+
+	echo "*** BUILD PROCESS COMPLETED SUCCESSFULLY ***"
+}
+
 
 function do_load_module(){
 	hint=${1:-""}
@@ -790,6 +921,9 @@ case $action in
 			;;					 
 	build-user-tools) do_build 1 | tee build_user.log
 			exit 0
+			;;
+	build-riscv*) do_build_riscv $2 $3
+			exit 0	
 			;;
 	build-android-odroid*) do_build_android_odroid $2 $3
 			exit 0	
